lesson_news_epage:
    pattern:  /news/{page}
    defaults: { _controller: LessonStartBundle:News:index, page:1 }
    requirements:
            page:  \d+
            _method:  GET

lesson_start_homepage:
    pattern:  /{_locale}
    defaults: { _controller: LessonStartBundle:Default:index, _locale:en }
    requirements:
            _locale:  en|ru|fr|de|es|it|ja|zh|no|tr|pt
            _method:  GET